// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Opiniometro_WebAppUITest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Despliegue de la Descripcion del Comentario Adicional
        /// </summary>
        public void DespliegueDescripcionComentario()
        {
            #region Variable Declarations
            HtmlComboBox uITieneObservacionComboBox = this.UIOpiniómetroUCRInternWindow.UIOpiniómetroUCRDocument3.UITieneObservacionComboBox;
            HtmlEdit uIEtiquetaObservacionEdit1 = this.UIOpiniómetroUCRInternWindow.UIOpiniómetroUCRDocument3.UIEtiquetaObservacionEdit1;
            #endregion

            // Select 'Sí' in 'TieneObservacion' combo box
            uITieneObservacionComboBox.SelectedItem = this.DespliegueDescripcionComentarioParams.UITieneObservacionComboBoxSelectedItem;

            // Type 'Despliegue' in 'EtiquetaObservacion' text box
            uIEtiquetaObservacionEdit1.Text = this.DespliegueDescripcionComentarioParams.UIEtiquetaObservacionEdit1Text;
        }
        
        /// <summary>
        /// Se inicializa explorador
        /// </summary>
        public void InicializarExplorador()
        {
            #region Variable Declarations
            HtmlHyperlink uILasdurasrevelacionesHyperlink = this.UIHomePageInternetExplWindow.UIHotmailOutlooknoticiDocument.UIMainCustom.UILasdurasrevelacionesHyperlink;
            HtmlIFrame uIUtif_banner1_homepagFrame = this.UIHomePageInternetExplWindow.UIHotmailOutlooknoticiDocument.UIUtif_banner1_homepagFrame;
            BrowserWindow uIHomePageInternetExplWindow = this.UIHomePageInternetExplWindow;
            #endregion

            // Go to web page 'http://go.microsoft.com/fwlink/p/?LinkId=255141' using new browser instance
            this.UIHomePageInternetExplWindow.LaunchUrl(new System.Uri(this.InicializarExploradorParams.UIHomePageInternetExplWindowUrl));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'Las duras revelaciones del exdirector del Sebin E...' link at (1, 1)
            Mouse.Hover(uILasdurasrevelacionesHyperlink, new Point(1, 1));

            // Mouse hover 'utif_banner1_homepage_container_45c20849-fc0e-4a6d...' frame at (1, 1)
            Mouse.Hover(uIUtif_banner1_homepagFrame, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Go to web page 'http://localhost/Opiniometro_WebApp'
            uIHomePageInternetExplWindow.NavigateToUrl(new System.Uri(this.InicializarExploradorParams.UIHomePageInternetExplWindowUrl1));
        }
        
        /// <summary>
        /// El usuario ingresa a su sesion
        /// </summary>
        public void login()
        {
            #region Variable Declarations
            HtmlEdit uICorreoInstitucionalEdit = this.UIOpiniómetroUCRInternWindow.UIOpiniómetroUCRDocument.UICorreoInstitucionalEdit;
            HtmlEdit uIContrasenaEdit = this.UIOpiniómetroUCRInternWindow.UIOpiniómetroUCRDocument.UIContrasenaEdit;
            HtmlInputButton uIIngresarButton = this.UIOpiniómetroUCRInternWindow.UIOpiniómetroUCRDocument.UIIngresarButton;
            #endregion

            // Type 'jose.mejiasrojas@ucr.ac.cr' in 'CorreoInstitucional' text box
            uICorreoInstitucionalEdit.Text = this.loginParams.UICorreoInstitucionalEditText;

            // Type '********' in 'Contrasena' text box
            uIContrasenaEdit.Password = this.loginParams.UIContrasenaEditPassword;

            // Click 'Ingresar' button
            Mouse.Click(uIIngresarButton, new Point(41, 26));
        }
        
        /// <summary>
        /// Prueba para Ingreso a la Aplicacion
        /// </summary>
        public void PruebaIngresoAplicacion()
        {
            #region Variable Declarations
            WinMenuItem uIAddressMenuItem = this.UIHomePageInternetExplWindow.UIAddressComboControlToolBar.UIAddressMenuItem;
            BrowserWindow uIHomePageInternetExplWindow = this.UIHomePageInternetExplWindow;
            #endregion

            // Go to web page 'http://go.microsoft.com/fwlink/p/?LinkId=255141' using new browser instance
            this.UIHomePageInternetExplWindow.LaunchUrl(new System.Uri(this.PruebaIngresoAplicacionParams.UIHomePageInternetExplWindowUrl));

            // Click 'Address' menu item
            Mouse.Click(uIAddressMenuItem, new Point(230, 4));

            // Go to web page 'http://localhost/Opiniometro_WebApp'
            uIHomePageInternetExplWindow.NavigateToUrl(new System.Uri(this.PruebaIngresoAplicacionParams.UIHomePageInternetExplWindowUrl1));
        }
        
        /// <summary>
        /// Se intenta crear una pregunta
        /// </summary>
        public void PruebaIntentoCrearPregunta()
        {
            #region Variable Declarations
            HtmlEdit uICorreoInstitucionalEdit = this.UIOpiniómetroUCRInternWindow.UIOpiniómetroUCRDocument.UICorreoInstitucionalEdit;
            HtmlInputButton uIIngresarButton = this.UIOpiniómetroUCRInternWindow.UIOpiniómetroUCRDocument.UIIngresarButton;
            HtmlInputButton uIAceptarButton = this.UIOpiniómetroUCRInternWindow.UIOpiniómetroUCRDocument1.UIAceptarButton;
            WinMenuItem uIAddressMenuItem = this.UIOpiniómetroUCRInternWindow.UIAddressComboControlToolBar.UIAddressMenuItem;
            BrowserWindow uIOpiniómetroUCRInternWindow = this.UIOpiniómetroUCRInternWindow;
            #endregion

            // Type '' in 'CorreoInstitucional' text box
            uICorreoInstitucionalEdit.Text = this.PruebaIntentoCrearPreguntaParams.UICorreoInstitucionalEditText;

            // Click 'CorreoInstitucional' text box
            Mouse.Click(uICorreoInstitucionalEdit, new Point(39, 13));

            // Type 'admin@ucr.ac.cr' in 'CorreoInstitucional' text box
            uICorreoInstitucionalEdit.Text = this.PruebaIntentoCrearPreguntaParams.UICorreoInstitucionalEditText1;

            // Click 'Ingresar' button
            Mouse.Click(uIIngresarButton, new Point(20, 25));

            // Click 'Aceptar' button
            Mouse.Click(uIAceptarButton, new Point(24, 11));

            // Click 'Address' menu item
            Mouse.Click(uIAddressMenuItem, new Point(234, 3));

            // Go to web page 'http://localhost/Opiniometro_WebApp/Item/create'
            uIOpiniómetroUCRInternWindow.NavigateToUrl(new System.Uri(this.PruebaIntentoCrearPreguntaParams.UIOpiniómetroUCRInternWindowUrl));
        }
        
        /// <summary>
        /// El estudiante ingresa a sus cursos matriculados y que tiene un formulario asignado
        /// </summary>
        public void IngresarCursosMatriculados()
        {
            #region Variable Declarations
            HtmlComboBox uIPerfilSeleccionadoComboBox = this.UIOpiniómetroUCRInternWindow.UIOpiniómetroUCRDocument1.UIPerfilSeleccionadoComboBox;
            HtmlInputButton uIAceptarButton = this.UIOpiniómetroUCRInternWindow.UIOpiniómetroUCRDocument1.UIAceptarButton;
            HtmlHyperlink uIEvaluacionesHyperlink = this.UIOpiniómetroUCRInternWindow.UIOpiniómetroUCRDocument2.UIEvaluacionesHyperlink;
            HtmlHyperlink uIEvaluarprofesoresHyperlink = this.UIOpiniómetroUCRInternWindow.UIOpiniómetroUCRDocument2.UIEvaluarprofesoresHyperlink;
            #endregion

            // Select 'Estudiante' in 'perfilSeleccionado' combo box
            uIPerfilSeleccionadoComboBox.SelectedItem = this.IngresarCursosMatriculadosParams.UIPerfilSeleccionadoComboBoxSelectedItem;

            // Click 'Aceptar' button
            Mouse.Click(uIAceptarButton, new Point(45, 15));

            // Click 'Evaluaciones' link
            Mouse.Click(uIEvaluacionesHyperlink, new Point(108, 22));

            // Click 'Evaluar profesores' link
            Mouse.Click(uIEvaluarprofesoresHyperlink, new Point(83, 18));
        }
        
        /// <summary>
        /// Se valida el ingreso al formulario
        /// </summary>
        public void validacionEnlace()
        {
            #region Variable Declarations
            HtmlHyperlink uIEvaluacióndeProfesorHyperlink = this.UIOpiniómetroUCRInternWindow.UIOpiniómetroUCRDocument4.UITablagruposMatriculaTable.UIEvaluacióndeProfesorHyperlink;
            #endregion

            // Click 'Evaluación de Profesores' link
            Mouse.Click(uIEvaluacióndeProfesorHyperlink, new Point(91, 7));
        }
        
        #region Properties
        public virtual DespliegueDescripcionComentarioParams DespliegueDescripcionComentarioParams
        {
            get
            {
                if ((this.mDespliegueDescripcionComentarioParams == null))
                {
                    this.mDespliegueDescripcionComentarioParams = new DespliegueDescripcionComentarioParams();
                }
                return this.mDespliegueDescripcionComentarioParams;
            }
        }
        
        public virtual InicializarExploradorParams InicializarExploradorParams
        {
            get
            {
                if ((this.mInicializarExploradorParams == null))
                {
                    this.mInicializarExploradorParams = new InicializarExploradorParams();
                }
                return this.mInicializarExploradorParams;
            }
        }
        
        public virtual loginParams loginParams
        {
            get
            {
                if ((this.mloginParams == null))
                {
                    this.mloginParams = new loginParams();
                }
                return this.mloginParams;
            }
        }
        
        public virtual PruebaIngresoAplicacionParams PruebaIngresoAplicacionParams
        {
            get
            {
                if ((this.mPruebaIngresoAplicacionParams == null))
                {
                    this.mPruebaIngresoAplicacionParams = new PruebaIngresoAplicacionParams();
                }
                return this.mPruebaIngresoAplicacionParams;
            }
        }
        
        public virtual PruebaIntentoCrearPreguntaParams PruebaIntentoCrearPreguntaParams
        {
            get
            {
                if ((this.mPruebaIntentoCrearPreguntaParams == null))
                {
                    this.mPruebaIntentoCrearPreguntaParams = new PruebaIntentoCrearPreguntaParams();
                }
                return this.mPruebaIntentoCrearPreguntaParams;
            }
        }
        
        public virtual IngresarCursosMatriculadosParams IngresarCursosMatriculadosParams
        {
            get
            {
                if ((this.mIngresarCursosMatriculadosParams == null))
                {
                    this.mIngresarCursosMatriculadosParams = new IngresarCursosMatriculadosParams();
                }
                return this.mIngresarCursosMatriculadosParams;
            }
        }
        
        public UIStartWindow UIStartWindow
        {
            get
            {
                if ((this.mUIStartWindow == null))
                {
                    this.mUIStartWindow = new UIStartWindow();
                }
                return this.mUIStartWindow;
            }
        }
        
        public UIHomePageInternetExplWindow UIHomePageInternetExplWindow
        {
            get
            {
                if ((this.mUIHomePageInternetExplWindow == null))
                {
                    this.mUIHomePageInternetExplWindow = new UIHomePageInternetExplWindow();
                }
                return this.mUIHomePageInternetExplWindow;
            }
        }
        
        public UIOpiniómetroUCRInternWindow UIOpiniómetroUCRInternWindow
        {
            get
            {
                if ((this.mUIOpiniómetroUCRInternWindow == null))
                {
                    this.mUIOpiniómetroUCRInternWindow = new UIOpiniómetroUCRInternWindow();
                }
                return this.mUIOpiniómetroUCRInternWindow;
            }
        }
        #endregion
        
        #region Fields
        private DespliegueDescripcionComentarioParams mDespliegueDescripcionComentarioParams;
        
        private InicializarExploradorParams mInicializarExploradorParams;
        
        private loginParams mloginParams;
        
        private PruebaIngresoAplicacionParams mPruebaIngresoAplicacionParams;
        
        private PruebaIntentoCrearPreguntaParams mPruebaIntentoCrearPreguntaParams;
        
        private IngresarCursosMatriculadosParams mIngresarCursosMatriculadosParams;
        
        private UIStartWindow mUIStartWindow;
        
        private UIHomePageInternetExplWindow mUIHomePageInternetExplWindow;
        
        private UIOpiniómetroUCRInternWindow mUIOpiniómetroUCRInternWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'DespliegueDescripcionComentario'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class DespliegueDescripcionComentarioParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'Sí' in 'TieneObservacion' combo box
        /// </summary>
        public string UITieneObservacionComboBoxSelectedItem = "Sí";
        
        /// <summary>
        /// Type 'Despliegue' in 'EtiquetaObservacion' text box
        /// </summary>
        public string UIEtiquetaObservacionEdit1Text = "Despliegue";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'InicializarExplorador'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class InicializarExploradorParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://go.microsoft.com/fwlink/p/?LinkId=255141' using new browser instance
        /// </summary>
        public string UIHomePageInternetExplWindowUrl = "http://go.microsoft.com/fwlink/p/?LinkId=255141";
        
        /// <summary>
        /// Go to web page 'http://localhost/Opiniometro_WebApp'
        /// </summary>
        public string UIHomePageInternetExplWindowUrl1 = "http://localhost/Opiniometro_WebApp";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'login'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class loginParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'jose.mejiasrojas@ucr.ac.cr' in 'CorreoInstitucional' text box
        /// </summary>
        public string UICorreoInstitucionalEditText = "jose.mejiasrojas@ucr.ac.cr";
        
        /// <summary>
        /// Type '********' in 'Contrasena' text box
        /// </summary>
        public string UIContrasenaEditPassword = "MTnqGLWWNjOWwjF8wGxtdQhZ43ocezNy";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'PruebaIngresoAplicacion'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class PruebaIngresoAplicacionParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://go.microsoft.com/fwlink/p/?LinkId=255141' using new browser instance
        /// </summary>
        public string UIHomePageInternetExplWindowUrl = "http://go.microsoft.com/fwlink/p/?LinkId=255141";
        
        /// <summary>
        /// Go to web page 'http://localhost/Opiniometro_WebApp'
        /// </summary>
        public string UIHomePageInternetExplWindowUrl1 = "http://localhost/Opiniometro_WebApp";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'PruebaIntentoCrearPregunta'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class PruebaIntentoCrearPreguntaParams
    {
        
        #region Fields
        /// <summary>
        /// Type '' in 'CorreoInstitucional' text box
        /// </summary>
        public string UICorreoInstitucionalEditText = "";
        
        /// <summary>
        /// Type 'admin@ucr.ac.cr' in 'CorreoInstitucional' text box
        /// </summary>
        public string UICorreoInstitucionalEditText1 = "admin@ucr.ac.cr";
        
        /// <summary>
        /// Go to web page 'http://localhost/Opiniometro_WebApp/Item/create'
        /// </summary>
        public string UIOpiniómetroUCRInternWindowUrl = "http://localhost/Opiniometro_WebApp/Item/create";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'IngresarCursosMatriculados'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class IngresarCursosMatriculadosParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'Estudiante' in 'perfilSeleccionado' combo box
        /// </summary>
        public string UIPerfilSeleccionadoComboBoxSelectedItem = "Estudiante";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIStartWindow : WinWindow
    {
        
        public UIStartWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Start";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Start";
            this.WindowTitles.Add("Start");
            #endregion
        }
        
        #region Properties
        public WinButton UIStartButton
        {
            get
            {
                if ((this.mUIStartButton == null))
                {
                    this.mUIStartButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIStartButton.SearchProperties[WinButton.PropertyNames.Name] = "Start";
                    this.mUIStartButton.WindowTitles.Add("Start");
                    #endregion
                }
                return this.mUIStartButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIStartButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHomePageInternetExplWindow : BrowserWindow
    {
        
        public UIHomePageInternetExplWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Home Page";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Home Page");
            this.WindowTitles.Add("Hotmail, Outlook, noticias en video, viajes, autos, vacaciones, moda y mucho más " +
                    "- MSN Latinoam");
            this.WindowTitles.Add("Blank Page");
            this.WindowTitles.Add("http://localhost/Opiniometro_WebApp");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIAddressBarClient UIAddressBarClient
        {
            get
            {
                if ((this.mUIAddressBarClient == null))
                {
                    this.mUIAddressBarClient = new UIAddressBarClient(this);
                }
                return this.mUIAddressBarClient;
            }
        }
        
        public UIHotmailOutlooknoticiDocument UIHotmailOutlooknoticiDocument
        {
            get
            {
                if ((this.mUIHotmailOutlooknoticiDocument == null))
                {
                    this.mUIHotmailOutlooknoticiDocument = new UIHotmailOutlooknoticiDocument(this);
                }
                return this.mUIHotmailOutlooknoticiDocument;
            }
        }
        
        public UIAddressComboControlToolBar UIAddressComboControlToolBar
        {
            get
            {
                if ((this.mUIAddressComboControlToolBar == null))
                {
                    this.mUIAddressComboControlToolBar = new UIAddressComboControlToolBar(this);
                }
                return this.mUIAddressComboControlToolBar;
            }
        }
        #endregion
        
        #region Fields
        private UIAddressBarClient mUIAddressBarClient;
        
        private UIHotmailOutlooknoticiDocument mUIHotmailOutlooknoticiDocument;
        
        private UIAddressComboControlToolBar mUIAddressComboControlToolBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIAddressBarClient : WinClient
    {
        
        public UIAddressBarClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Address Bar";
            this.WindowTitles.Add("Home Page");
            this.WindowTitles.Add("Hotmail, Outlook, noticias en video, viajes, autos, vacaciones, moda y mucho más " +
                    "- MSN Latinoam");
            this.WindowTitles.Add("Blank Page");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAddressandsearchusinEdit
        {
            get
            {
                if ((this.mUIAddressandsearchusinEdit == null))
                {
                    this.mUIAddressandsearchusinEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAddressandsearchusinEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Address and search using Bing";
                    this.mUIAddressandsearchusinEdit.WindowTitles.Add("Home Page");
                    this.mUIAddressandsearchusinEdit.WindowTitles.Add("Hotmail, Outlook, noticias en video, viajes, autos, vacaciones, moda y mucho más " +
                            "- MSN Latinoam");
                    this.mUIAddressandsearchusinEdit.WindowTitles.Add("Blank Page");
                    #endregion
                }
                return this.mUIAddressandsearchusinEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAddressandsearchusinEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHotmailOutlooknoticiDocument : HtmlDocument
    {
        
        public UIHotmailOutlooknoticiDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Hotmail, Outlook, noticias en video, viajes, autos, vacaciones, moda y mucho más " +
                "- MSN Latinoamérica";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/es-xl/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://www.msn.com/es-xl/?ocid=iehp";
            this.WindowTitles.Add("Hotmail, Outlook, noticias en video, viajes, autos, vacaciones, moda y mucho más " +
                    "- MSN Latinoam");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIHeadercommonCustom
        {
            get
            {
                if ((this.mUIHeadercommonCustom == null))
                {
                    this.mUIHeadercommonCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIHeadercommonCustom.SearchProperties["TagName"] = "HEADER";
                    this.mUIHeadercommonCustom.SearchProperties["Id"] = "header-common";
                    this.mUIHeadercommonCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIHeadercommonCustom.FilterProperties["Class"] = "no-overlay";
                    this.mUIHeadercommonCustom.FilterProperties["ControlDefinition"] = "class=\"no-overlay\" id=\"header-common\" ro";
                    this.mUIHeadercommonCustom.FilterProperties["TagInstance"] = "1";
                    this.mUIHeadercommonCustom.WindowTitles.Add("Hotmail, Outlook, noticias en video, viajes, autos, vacaciones, moda y mucho más " +
                            "- MSN Latinoam");
                    #endregion
                }
                return this.mUIHeadercommonCustom;
            }
        }
        
        public UIMainCustom UIMainCustom
        {
            get
            {
                if ((this.mUIMainCustom == null))
                {
                    this.mUIMainCustom = new UIMainCustom(this);
                }
                return this.mUIMainCustom;
            }
        }
        
        public HtmlIFrame UIUtif_banner1_homepagFrame
        {
            get
            {
                if ((this.mUIUtif_banner1_homepagFrame == null))
                {
                    this.mUIUtif_banner1_homepagFrame = new HtmlIFrame(this);
                    #region Search Criteria
                    this.mUIUtif_banner1_homepagFrame.SearchProperties[HtmlFrame.PropertyNames.Id] = "utif_banner1_homepage_container_45c20849-fc0e-4a6d-8c41-3d87bb7527d4_aff64a2d-aa9" +
                        "f-4cbf-ab9d-ce2f7c3d5861";
                    this.mUIUtif_banner1_homepagFrame.SearchProperties[HtmlFrame.PropertyNames.Name] = "utif_banner1_homepage_container_45c20849-fc0e-4a6d-8c41-3d87bb7527d4_aff64a2d-aa9" +
                        "f-4cbf-ab9d-ce2f7c3d5861";
                    this.mUIUtif_banner1_homepagFrame.FilterProperties[HtmlFrame.PropertyNames.AbsolutePath] = null;
                    this.mUIUtif_banner1_homepagFrame.FilterProperties[HtmlFrame.PropertyNames.PageUrl] = null;
                    this.mUIUtif_banner1_homepagFrame.FilterProperties[HtmlFrame.PropertyNames.Title] = null;
                    this.mUIUtif_banner1_homepagFrame.FilterProperties[HtmlFrame.PropertyNames.Class] = null;
                    this.mUIUtif_banner1_homepagFrame.FilterProperties[HtmlFrame.PropertyNames.ControlDefinition] = "name=\"utif_banner1_homepage_container_45";
                    this.mUIUtif_banner1_homepagFrame.FilterProperties[HtmlFrame.PropertyNames.TagInstance] = "2";
                    this.mUIUtif_banner1_homepagFrame.WindowTitles.Add("Hotmail, Outlook, noticias en video, viajes, autos, vacaciones, moda y mucho más " +
                            "- MSN Latinoam");
                    #endregion
                }
                return this.mUIUtif_banner1_homepagFrame;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIHeadercommonCustom;
        
        private UIMainCustom mUIMainCustom;
        
        private HtmlIFrame mUIUtif_banner1_homepagFrame;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIMainCustom : HtmlCustom
    {
        
        public UIMainCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "main";
            this.SearchProperties["Id"] = "main";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=\"main\" role=\"main\" data-m=\'{\"i\":18,\"n";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("Hotmail, Outlook, noticias en video, viajes, autos, vacaciones, moda y mucho más " +
                    "- MSN Latinoam");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UILasdurasrevelacionesHyperlink
        {
            get
            {
                if ((this.mUILasdurasrevelacionesHyperlink == null))
                {
                    this.mUILasdurasrevelacionesHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUILasdurasrevelacionesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUILasdurasrevelacionesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUILasdurasrevelacionesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUILasdurasrevelacionesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = " Las duras revelaciones del exdirector del Sebin EL PAÍS  ";
                    this.mUILasdurasrevelacionesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/es-xl/noticias/venezuela/%E2%80%9Clas-torturas-en-venezuela-son-sistem%C3%A1tica" +
                        "s%E2%80%9D/ar-AAE8MF8";
                    this.mUILasdurasrevelacionesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUILasdurasrevelacionesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://www.msn.com/es-xl/noticias/venezuela/%e2%80%9clas-torturas-en-venezuela-so" +
                        "n-sistem%c3%a1ticas%e2%80%9d/ar-AAE8MF8?li=AAgh0dF";
                    this.mUILasdurasrevelacionesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUILasdurasrevelacionesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/es-xl/noticias/venezuela/%e2%80%9";
                    this.mUILasdurasrevelacionesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "51";
                    this.mUILasdurasrevelacionesHyperlink.WindowTitles.Add("Hotmail, Outlook, noticias en video, viajes, autos, vacaciones, moda y mucho más " +
                            "- MSN Latinoam");
                    #endregion
                }
                return this.mUILasdurasrevelacionesHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUILasdurasrevelacionesHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIAddressComboControlToolBar : WinToolBar
    {
        
        public UIAddressComboControlToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Address Combo Control";
            this.WindowTitles.Add("Hotmail, Outlook, noticias en video, viajes, autos, vacaciones, moda y mucho más " +
                    "- MSN Latinoam");
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIAddressMenuItem
        {
            get
            {
                if ((this.mUIAddressMenuItem == null))
                {
                    this.mUIAddressMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIAddressMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Address";
                    this.mUIAddressMenuItem.WindowTitles.Add("Hotmail, Outlook, noticias en video, viajes, autos, vacaciones, moda y mucho más " +
                            "- MSN Latinoam");
                    #endregion
                }
                return this.mUIAddressMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIAddressMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIOpiniómetroUCRInternWindow : BrowserWindow
    {
        
        public UIOpiniómetroUCRInternWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Opiniómetro@UCR";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Opiniómetro@UCR");
            this.WindowTitles.Add("http://localhost/Opiniometro_WebApp/Item/create");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIOpiniómetroUCRDocument UIOpiniómetroUCRDocument
        {
            get
            {
                if ((this.mUIOpiniómetroUCRDocument == null))
                {
                    this.mUIOpiniómetroUCRDocument = new UIOpiniómetroUCRDocument(this);
                }
                return this.mUIOpiniómetroUCRDocument;
            }
        }
        
        public UIOpiniómetroUCRDocument1 UIOpiniómetroUCRDocument1
        {
            get
            {
                if ((this.mUIOpiniómetroUCRDocument1 == null))
                {
                    this.mUIOpiniómetroUCRDocument1 = new UIOpiniómetroUCRDocument1(this);
                }
                return this.mUIOpiniómetroUCRDocument1;
            }
        }
        
        public UIAddressComboControlToolBar1 UIAddressComboControlToolBar
        {
            get
            {
                if ((this.mUIAddressComboControlToolBar == null))
                {
                    this.mUIAddressComboControlToolBar = new UIAddressComboControlToolBar1(this);
                }
                return this.mUIAddressComboControlToolBar;
            }
        }
        
        public UIOpiniómetroUCRDocument2 UIOpiniómetroUCRDocument2
        {
            get
            {
                if ((this.mUIOpiniómetroUCRDocument2 == null))
                {
                    this.mUIOpiniómetroUCRDocument2 = new UIOpiniómetroUCRDocument2(this);
                }
                return this.mUIOpiniómetroUCRDocument2;
            }
        }
        
        public UIOpiniómetroUCRDocument11 UIOpiniómetroUCRDocument11
        {
            get
            {
                if ((this.mUIOpiniómetroUCRDocument11 == null))
                {
                    this.mUIOpiniómetroUCRDocument11 = new UIOpiniómetroUCRDocument11(this);
                }
                return this.mUIOpiniómetroUCRDocument11;
            }
        }
        
        public UIOpiniómetroUCRDocument3 UIOpiniómetroUCRDocument3
        {
            get
            {
                if ((this.mUIOpiniómetroUCRDocument3 == null))
                {
                    this.mUIOpiniómetroUCRDocument3 = new UIOpiniómetroUCRDocument3(this);
                }
                return this.mUIOpiniómetroUCRDocument3;
            }
        }
        
        public UIOpiniómetroUCRDocument4 UIOpiniómetroUCRDocument4
        {
            get
            {
                if ((this.mUIOpiniómetroUCRDocument4 == null))
                {
                    this.mUIOpiniómetroUCRDocument4 = new UIOpiniómetroUCRDocument4(this);
                }
                return this.mUIOpiniómetroUCRDocument4;
            }
        }
        #endregion
        
        #region Fields
        private UIOpiniómetroUCRDocument mUIOpiniómetroUCRDocument;
        
        private UIOpiniómetroUCRDocument1 mUIOpiniómetroUCRDocument1;
        
        private UIAddressComboControlToolBar1 mUIAddressComboControlToolBar;
        
        private UIOpiniómetroUCRDocument2 mUIOpiniómetroUCRDocument2;
        
        private UIOpiniómetroUCRDocument11 mUIOpiniómetroUCRDocument11;
        
        private UIOpiniómetroUCRDocument3 mUIOpiniómetroUCRDocument3;
        
        private UIOpiniómetroUCRDocument4 mUIOpiniómetroUCRDocument4;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIOpiniómetroUCRDocument : HtmlDocument
    {
        
        public UIOpiniómetroUCRDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Opiniómetro@UCR";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Opiniometro_WebApp/Auth/Login";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost/Opiniometro_WebApp/Auth/Login?ReturnUrl=%2FOpiniometro_WebApp%2F" +
                "";
            this.WindowTitles.Add("Opiniómetro@UCR");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UICorreoInstitucionalEdit
        {
            get
            {
                if ((this.mUICorreoInstitucionalEdit == null))
                {
                    this.mUICorreoInstitucionalEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUICorreoInstitucionalEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUICorreoInstitucionalEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "CorreoInstitucional";
                    this.mUICorreoInstitucionalEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUICorreoInstitucionalEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUICorreoInstitucionalEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUICorreoInstitucionalEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUICorreoInstitucionalEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"CorreoInstitucional\" class=\"form-c";
                    this.mUICorreoInstitucionalEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUICorreoInstitucionalEdit.WindowTitles.Add("Opiniómetro@UCR");
                    #endregion
                }
                return this.mUICorreoInstitucionalEdit;
            }
        }
        
        public HtmlInputButton UIIngresarButton
        {
            get
            {
                if ((this.mUIIngresarButton == null))
                {
                    this.mUIIngresarButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIIngresarButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUIIngresarButton.SearchProperties[HtmlButton.PropertyNames.Name] = "Ingresar";
                    this.mUIIngresarButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Ingresar";
                    this.mUIIngresarButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIIngresarButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIIngresarButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-default";
                    this.mUIIngresarButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "name=\"Ingresar\" class=\"btn btn-default\" ";
                    this.mUIIngresarButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "3";
                    this.mUIIngresarButton.WindowTitles.Add("Opiniómetro@UCR");
                    #endregion
                }
                return this.mUIIngresarButton;
            }
        }
        
        public HtmlEdit UIContrasenaEdit
        {
            get
            {
                if ((this.mUIContrasenaEdit == null))
                {
                    this.mUIContrasenaEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIContrasenaEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUIContrasenaEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Contrasena";
                    this.mUIContrasenaEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIContrasenaEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIContrasenaEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIContrasenaEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIContrasenaEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Contrasena\" class=\"form-control\" t";
                    this.mUIContrasenaEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIContrasenaEdit.WindowTitles.Add("Opiniómetro@UCR");
                    #endregion
                }
                return this.mUIContrasenaEdit;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUICorreoInstitucionalEdit;
        
        private HtmlInputButton mUIIngresarButton;
        
        private HtmlEdit mUIContrasenaEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIOpiniómetroUCRDocument1 : HtmlDocument
    {
        
        public UIOpiniómetroUCRDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Opiniómetro@UCR";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Opiniometro_WebApp/Perfil/Cambiar";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost/Opiniometro_WebApp/Perfil/Cambiar";
            this.WindowTitles.Add("Opiniómetro@UCR");
            #endregion
        }
        
        #region Properties
        public HtmlInputButton UIAceptarButton
        {
            get
            {
                if ((this.mUIAceptarButton == null))
                {
                    this.mUIAceptarButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIAceptarButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUIAceptarButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIAceptarButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Aceptar";
                    this.mUIAceptarButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIAceptarButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIAceptarButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-default";
                    this.mUIAceptarButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-default\" style=\"margin-ri";
                    this.mUIAceptarButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "1";
                    this.mUIAceptarButton.WindowTitles.Add("Opiniómetro@UCR");
                    #endregion
                }
                return this.mUIAceptarButton;
            }
        }
        
        public HtmlComboBox UIPerfilSeleccionadoComboBox
        {
            get
            {
                if ((this.mUIPerfilSeleccionadoComboBox == null))
                {
                    this.mUIPerfilSeleccionadoComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUIPerfilSeleccionadoComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "perfilSeleccionado";
                    this.mUIPerfilSeleccionadoComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "perfilSeleccionado";
                    this.mUIPerfilSeleccionadoComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = null;
                    this.mUIPerfilSeleccionadoComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUIPerfilSeleccionadoComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUIPerfilSeleccionadoComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "3";
                    this.mUIPerfilSeleccionadoComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "form-control";
                    this.mUIPerfilSeleccionadoComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"perfilSeleccionado\" class=\"form-co";
                    this.mUIPerfilSeleccionadoComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "1";
                    this.mUIPerfilSeleccionadoComboBox.WindowTitles.Add("Opiniómetro@UCR");
                    #endregion
                }
                return this.mUIPerfilSeleccionadoComboBox;
            }
        }
        #endregion
        
        #region Fields
        private HtmlInputButton mUIAceptarButton;
        
        private HtmlComboBox mUIPerfilSeleccionadoComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIAddressComboControlToolBar1 : WinToolBar
    {
        
        public UIAddressComboControlToolBar1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Address Combo Control";
            this.WindowTitles.Add("Opiniómetro@UCR");
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIAddressMenuItem
        {
            get
            {
                if ((this.mUIAddressMenuItem == null))
                {
                    this.mUIAddressMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIAddressMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Address";
                    this.mUIAddressMenuItem.WindowTitles.Add("Opiniómetro@UCR");
                    #endregion
                }
                return this.mUIAddressMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIAddressMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIOpiniómetroUCRDocument2 : HtmlDocument
    {
        
        public UIOpiniómetroUCRDocument2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Opiniómetro@UCR";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Opiniometro_WebApp/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost/Opiniometro_WebApp/";
            this.WindowTitles.Add("Opiniómetro@UCR");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIEvaluacionesHyperlink
        {
            get
            {
                if ((this.mUIEvaluacionesHyperlink == null))
                {
                    this.mUIEvaluacionesHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIEvaluacionesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIEvaluacionesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIEvaluacionesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIEvaluacionesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Evaluaciones";
                    this.mUIEvaluacionesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Opiniometro_WebApp/";
                    this.mUIEvaluacionesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIEvaluacionesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost/Opiniometro_WebApp/#";
                    this.mUIEvaluacionesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "dropdown-toggle";
                    this.mUIEvaluacionesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"dropdown-toggle\" role=\"button\" ar";
                    this.mUIEvaluacionesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "13";
                    this.mUIEvaluacionesHyperlink.WindowTitles.Add("Opiniómetro@UCR");
                    #endregion
                }
                return this.mUIEvaluacionesHyperlink;
            }
        }
        
        public HtmlHyperlink UIInsertarItemsHyperlink
        {
            get
            {
                if ((this.mUIInsertarItemsHyperlink == null))
                {
                    this.mUIInsertarItemsHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIInsertarItemsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIInsertarItemsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIInsertarItemsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIInsertarItemsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Insertar Items";
                    this.mUIInsertarItemsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Opiniometro_WebApp/Item";
                    this.mUIInsertarItemsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIInsertarItemsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost/Opiniometro_WebApp/Item";
                    this.mUIInsertarItemsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIInsertarItemsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Opiniometro_WebApp/Item\"";
                    this.mUIInsertarItemsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "18";
                    this.mUIInsertarItemsHyperlink.WindowTitles.Add("Opiniómetro@UCR");
                    #endregion
                }
                return this.mUIInsertarItemsHyperlink;
            }
        }
        
        public HtmlHyperlink UIEvaluarprofesoresHyperlink
        {
            get
            {
                if ((this.mUIEvaluarprofesoresHyperlink == null))
                {
                    this.mUIEvaluarprofesoresHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIEvaluarprofesoresHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIEvaluarprofesoresHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIEvaluarprofesoresHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIEvaluarprofesoresHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Evaluar profesores";
                    this.mUIEvaluarprofesoresHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Opiniometro_WebApp/CursosMatriculados";
                    this.mUIEvaluarprofesoresHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIEvaluarprofesoresHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost/Opiniometro_WebApp/CursosMatriculados";
                    this.mUIEvaluarprofesoresHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIEvaluarprofesoresHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Opiniometro_WebApp/CursosMatricul";
                    this.mUIEvaluarprofesoresHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "17";
                    this.mUIEvaluarprofesoresHyperlink.WindowTitles.Add("Opiniómetro@UCR");
                    #endregion
                }
                return this.mUIEvaluarprofesoresHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIEvaluacionesHyperlink;
        
        private HtmlHyperlink mUIInsertarItemsHyperlink;
        
        private HtmlHyperlink mUIEvaluarprofesoresHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIOpiniómetroUCRDocument11 : HtmlDocument
    {
        
        public UIOpiniómetroUCRDocument11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Opiniómetro@UCR";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Opiniometro_WebApp/Item";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost/Opiniometro_WebApp/Item";
            this.WindowTitles.Add("Opiniómetro@UCR");
            #endregion
        }
        
        #region Properties
        public UIVistaitemTable UIVistaitemTable
        {
            get
            {
                if ((this.mUIVistaitemTable == null))
                {
                    this.mUIVistaitemTable = new UIVistaitemTable(this);
                }
                return this.mUIVistaitemTable;
            }
        }
        
        public HtmlInputButton UICrearNuevaPreguntaButton
        {
            get
            {
                if ((this.mUICrearNuevaPreguntaButton == null))
                {
                    this.mUICrearNuevaPreguntaButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUICrearNuevaPreguntaButton.SearchProperties[HtmlButton.PropertyNames.Id] = "botonNuevaPregunta";
                    this.mUICrearNuevaPreguntaButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUICrearNuevaPreguntaButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Crear Nueva Pregunta";
                    this.mUICrearNuevaPreguntaButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUICrearNuevaPreguntaButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUICrearNuevaPreguntaButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-secondary";
                    this.mUICrearNuevaPreguntaButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-secondary\" id=\"botonNueva";
                    this.mUICrearNuevaPreguntaButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "1";
                    this.mUICrearNuevaPreguntaButton.WindowTitles.Add("Opiniómetro@UCR");
                    #endregion
                }
                return this.mUICrearNuevaPreguntaButton;
            }
        }
        #endregion
        
        #region Fields
        private UIVistaitemTable mUIVistaitemTable;
        
        private HtmlInputButton mUICrearNuevaPreguntaButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIVistaitemTable : HtmlTable
    {
        
        public UIVistaitemTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = "vistaitem";
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "Código \r\n\r\nPlanteamiento de la pregunta ";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "class=\"table\" id=\"vistaitem\"";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "11";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "5";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = "table";
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("Opiniómetro@UCR");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIOpiniometro_WebAppCoImage
        {
            get
            {
                if ((this.mUIOpiniometro_WebAppCoImage == null))
                {
                    this.mUIOpiniometro_WebAppCoImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIOpiniometro_WebAppCoImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUIOpiniometro_WebAppCoImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIOpiniometro_WebAppCoImage.SearchProperties[HtmlImage.PropertyNames.Alt] = null;
                    this.mUIOpiniometro_WebAppCoImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/Opiniometro_WebApp/Content/img/plus.png";
                    this.mUIOpiniometro_WebAppCoImage.FilterProperties[HtmlImage.PropertyNames.Src] = "http://localhost/Opiniometro_WebApp/Content/img/plus.png";
                    this.mUIOpiniometro_WebAppCoImage.FilterProperties[HtmlImage.PropertyNames.Class] = null;
                    this.mUIOpiniometro_WebAppCoImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "src=\"/Opiniometro_WebApp/Content/img/plu";
                    this.mUIOpiniometro_WebAppCoImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "1";
                    this.mUIOpiniometro_WebAppCoImage.WindowTitles.Add("Opiniómetro@UCR");
                    #endregion
                }
                return this.mUIOpiniometro_WebAppCoImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIOpiniometro_WebAppCoImage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIOpiniómetroUCRDocument3 : HtmlDocument
    {
        
        public UIOpiniómetroUCRDocument3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Opiniómetro@UCR";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Opiniometro_WebApp/Item/Create";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost/Opiniometro_WebApp/Item/Create";
            this.WindowTitles.Add("Opiniómetro@UCR");
            #endregion
        }
        
        #region Properties
        public HtmlComboBox UITieneObservacionComboBox
        {
            get
            {
                if ((this.mUITieneObservacionComboBox == null))
                {
                    this.mUITieneObservacionComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUITieneObservacionComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "comboboxtieneobservacion";
                    this.mUITieneObservacionComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "TieneObservacion";
                    this.mUITieneObservacionComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = null;
                    this.mUITieneObservacionComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUITieneObservacionComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUITieneObservacionComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "3";
                    this.mUITieneObservacionComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "form-control valid";
                    this.mUITieneObservacionComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"TieneObservacion\" class=\"form-cont";
                    this.mUITieneObservacionComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "3";
                    this.mUITieneObservacionComboBox.WindowTitles.Add("Opiniómetro@UCR");
                    #endregion
                }
                return this.mUITieneObservacionComboBox;
            }
        }
        
        public HtmlEdit UIEtiquetaObservacionEdit1
        {
            get
            {
                if ((this.mUIEtiquetaObservacionEdit1 == null))
                {
                    this.mUIEtiquetaObservacionEdit1 = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIEtiquetaObservacionEdit1.SearchProperties[HtmlEdit.PropertyNames.Id] = "EtiquetaObservacion";
                    this.mUIEtiquetaObservacionEdit1.SearchProperties[HtmlEdit.PropertyNames.Name] = "EtiquetaObservacion";
                    this.mUIEtiquetaObservacionEdit1.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIEtiquetaObservacionEdit1.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIEtiquetaObservacionEdit1.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIEtiquetaObservacionEdit1.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control text-box single-line valid";
                    this.mUIEtiquetaObservacionEdit1.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"EtiquetaObservacion\" class=\"form-c";
                    this.mUIEtiquetaObservacionEdit1.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    this.mUIEtiquetaObservacionEdit1.WindowTitles.Add("Opiniómetro@UCR");
                    #endregion
                }
                return this.mUIEtiquetaObservacionEdit1;
            }
        }
        #endregion
        
        #region Fields
        private HtmlComboBox mUITieneObservacionComboBox;
        
        private HtmlEdit mUIEtiquetaObservacionEdit1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIOpiniómetroUCRDocument4 : HtmlDocument
    {
        
        public UIOpiniómetroUCRDocument4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Opiniómetro@UCR";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Opiniometro_WebApp/CursosMatriculados";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost/Opiniometro_WebApp/CursosMatriculados";
            this.WindowTitles.Add("Opiniómetro@UCR");
            #endregion
        }
        
        #region Properties
        public UITablagruposMatriculaTable UITablagruposMatriculaTable
        {
            get
            {
                if ((this.mUITablagruposMatriculaTable == null))
                {
                    this.mUITablagruposMatriculaTable = new UITablagruposMatriculaTable(this);
                }
                return this.mUITablagruposMatriculaTable;
            }
        }
        #endregion
        
        #region Fields
        private UITablagruposMatriculaTable mUITablagruposMatriculaTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UITablagruposMatriculaTable : HtmlTable
    {
        
        public UITablagruposMatriculaTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = "tabla-gruposMatriculado";
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "Sigla \r\n\r\nCurso \r\n\r\nSemestre \r\n\r\nAño \r\n\r";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "width=\"100\" class=\"table table-sm table-hover\" id=\"tabla-gruposMatriculado\" cells" +
                "pacing=\"0\"";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "2";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "6";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = "table table-sm table-hover";
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("Opiniómetro@UCR");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIEvaluacióndeProfesorHyperlink
        {
            get
            {
                if ((this.mUIEvaluacióndeProfesorHyperlink == null))
                {
                    this.mUIEvaluacióndeProfesorHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIEvaluacióndeProfesorHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIEvaluacióndeProfesorHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIEvaluacióndeProfesorHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIEvaluacióndeProfesorHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Evaluación de Profesores";
                    this.mUIEvaluacióndeProfesorHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Opiniometro_WebApp/FormularioCurso";
                    this.mUIEvaluacióndeProfesorHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIEvaluacióndeProfesorHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost/Opiniometro_WebApp/FormularioCurso?cedulaEstudiante=116720500&co" +
                        "digoForm=131313&anno=0&semestre=0&numGrupo=0";
                    this.mUIEvaluacióndeProfesorHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIEvaluacióndeProfesorHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Opiniometro_WebApp/FormularioCurs";
                    this.mUIEvaluacióndeProfesorHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIEvaluacióndeProfesorHyperlink.WindowTitles.Add("Opiniómetro@UCR");
                    #endregion
                }
                return this.mUIEvaluacióndeProfesorHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIEvaluacióndeProfesorHyperlink;
        #endregion
    }
}
