// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Opiniometro_WebAppUITest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Se inicializa el explorador web
        /// </summary>
        public void InicializarExplorador()
        {
            #region Variable Declarations
            HtmlHyperlink uIOfficeHyperlink = this.UIHotmailOutlooknoticiWindow.UIHotmailOutlooknoticiDocument.UIMainCustom.UIOfficeHyperlink;
            BrowserWindow uIHotmailOutlooknoticiWindow = this.UIHotmailOutlooknoticiWindow;
            #endregion

            // Go to web page 'http://go.microsoft.com/fwlink/p/?LinkId=255141' using new browser instance
            this.UIHotmailOutlooknoticiWindow.LaunchUrl(new System.Uri(this.InicializarExploradorParams.UIHotmailOutlooknoticiWindowUrl));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'Office' link at (1, 1)
            Mouse.Hover(uIOfficeHyperlink, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Go to web page 'http://localhost/Opiniometro_WebApp'
            uIHotmailOutlooknoticiWindow.NavigateToUrl(new System.Uri(this.InicializarExploradorParams.UIHotmailOutlooknoticiWindowUrl1));
        }
        
        /// <summary>
        /// El usuario inicia sesion
        /// </summary>
        public void loginUsuario()
        {
            #region Variable Declarations
            HtmlEdit uICorreoInstitucionalEdit = this.UIOpiniómetroUCRInternWindow.UIOpiniómetroUCRDocument1.UICorreoInstitucionalEdit;
            HtmlEdit uIContrasenaEdit = this.UIOpiniómetroUCRInternWindow.UIOpiniómetroUCRDocument1.UIContrasenaEdit;
            HtmlInputButton uIIngresarButton = this.UIOpiniómetroUCRInternWindow.UIOpiniómetroUCRDocument1.UIIngresarButton;
            #endregion

            // Type 'jose.mejiasrojas@ucr.ac.cr' in 'CorreoInstitucional' text box
            uICorreoInstitucionalEdit.Text = this.loginUsuarioParams.UICorreoInstitucionalEditText;

            // Type '********' in 'Contrasena' text box
            uIContrasenaEdit.Password = this.loginUsuarioParams.UIContrasenaEditPassword;

            // Click 'Ingresar' button
            Mouse.Click(uIIngresarButton, new Point(24, 14));
        }
        
        /// <summary>
        /// Se valida el enlace para entrar a formulario
        /// </summary>
        public void validacionEnlace()
        {
            #region Variable Declarations
            HtmlHyperlink uIEvaluacióndeProfesorHyperlink = this.UIOpiniómetroUCRInternWindow.UIOpiniómetroUCRDocument.UITablagruposMatriculaTable.UIEvaluacióndeProfesorHyperlink;
            #endregion

            // Click 'Evaluación de Profesores' link
            Mouse.Click(uIEvaluacióndeProfesorHyperlink, new Point(79, 12));
        }
        
        /// <summary>
        /// El estudiante visualiza la lista de cursos que tiene matriculados y que tienen un formulario asignado
        /// </summary>
        public void IngresarCursosMatriculados()
        {
            #region Variable Declarations
            HtmlComboBox uIPerfilSeleccionadoComboBox = this.UIOpiniómetroUCRInternWindow.UIOpiniómetroUCRDocument2.UIPerfilSeleccionadoComboBox;
            HtmlInputButton uIAceptarButton = this.UIOpiniómetroUCRInternWindow.UIOpiniómetroUCRDocument2.UIAceptarButton;
            HtmlHyperlink uIEvaluacionesHyperlink = this.UIOpiniómetroUCRInternWindow.UIOpiniómetroUCRDocument11.UIEvaluacionesHyperlink;
            HtmlHyperlink uIEvaluarprofesoresHyperlink = this.UIOpiniómetroUCRInternWindow.UIOpiniómetroUCRDocument11.UIEvaluarprofesoresHyperlink;
            #endregion

            // Select 'Estudiante' in 'perfilSeleccionado' combo box
            uIPerfilSeleccionadoComboBox.SelectedItem = this.IngresarCursosMatriculadosParams.UIPerfilSeleccionadoComboBoxSelectedItem;

            // Click 'Aceptar' button
            Mouse.Click(uIAceptarButton, new Point(56, 15));

            // Click 'Evaluaciones' link
            Mouse.Click(uIEvaluacionesHyperlink, new Point(127, 33));

            // Click 'Evaluar profesores' link
            Mouse.Click(uIEvaluarprofesoresHyperlink, new Point(42, 15));
        }
        
        #region Properties
        public virtual InicializarExploradorParams InicializarExploradorParams
        {
            get
            {
                if ((this.mInicializarExploradorParams == null))
                {
                    this.mInicializarExploradorParams = new InicializarExploradorParams();
                }
                return this.mInicializarExploradorParams;
            }
        }
        
        public virtual loginUsuarioParams loginUsuarioParams
        {
            get
            {
                if ((this.mloginUsuarioParams == null))
                {
                    this.mloginUsuarioParams = new loginUsuarioParams();
                }
                return this.mloginUsuarioParams;
            }
        }
        
        public virtual IngresarCursosMatriculadosParams IngresarCursosMatriculadosParams
        {
            get
            {
                if ((this.mIngresarCursosMatriculadosParams == null))
                {
                    this.mIngresarCursosMatriculadosParams = new IngresarCursosMatriculadosParams();
                }
                return this.mIngresarCursosMatriculadosParams;
            }
        }
        
        public UIOpiniómetroUCRInternWindow UIOpiniómetroUCRInternWindow
        {
            get
            {
                if ((this.mUIOpiniómetroUCRInternWindow == null))
                {
                    this.mUIOpiniómetroUCRInternWindow = new UIOpiniómetroUCRInternWindow();
                }
                return this.mUIOpiniómetroUCRInternWindow;
            }
        }
        
        public UIHotmailOutlooknoticiWindow UIHotmailOutlooknoticiWindow
        {
            get
            {
                if ((this.mUIHotmailOutlooknoticiWindow == null))
                {
                    this.mUIHotmailOutlooknoticiWindow = new UIHotmailOutlooknoticiWindow();
                }
                return this.mUIHotmailOutlooknoticiWindow;
            }
        }
        #endregion
        
        #region Fields
        private InicializarExploradorParams mInicializarExploradorParams;
        
        private loginUsuarioParams mloginUsuarioParams;
        
        private IngresarCursosMatriculadosParams mIngresarCursosMatriculadosParams;
        
        private UIOpiniómetroUCRInternWindow mUIOpiniómetroUCRInternWindow;
        
        private UIHotmailOutlooknoticiWindow mUIHotmailOutlooknoticiWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'InicializarExplorador'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class InicializarExploradorParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://go.microsoft.com/fwlink/p/?LinkId=255141' using new browser instance
        /// </summary>
        public string UIHotmailOutlooknoticiWindowUrl = "http://go.microsoft.com/fwlink/p/?LinkId=255141";
        
        /// <summary>
        /// Go to web page 'http://localhost/Opiniometro_WebApp'
        /// </summary>
        public string UIHotmailOutlooknoticiWindowUrl1 = "http://localhost/Opiniometro_WebApp";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'loginUsuario'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class loginUsuarioParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'jose.mejiasrojas@ucr.ac.cr' in 'CorreoInstitucional' text box
        /// </summary>
        public string UICorreoInstitucionalEditText = "jose.mejiasrojas@ucr.ac.cr";
        
        /// <summary>
        /// Type '********' in 'Contrasena' text box
        /// </summary>
        public string UIContrasenaEditPassword = "MTnqGLWWNjOWwjF8wGxtdQhZ43ocezNy";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'IngresarCursosMatriculados'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class IngresarCursosMatriculadosParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'Estudiante' in 'perfilSeleccionado' combo box
        /// </summary>
        public string UIPerfilSeleccionadoComboBoxSelectedItem = "Estudiante";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIOpiniómetroUCRInternWindow : BrowserWindow
    {
        
        public UIOpiniómetroUCRInternWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Opiniómetro@UCR";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Opiniómetro@UCR");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIOpiniómetroUCRDocument UIOpiniómetroUCRDocument
        {
            get
            {
                if ((this.mUIOpiniómetroUCRDocument == null))
                {
                    this.mUIOpiniómetroUCRDocument = new UIOpiniómetroUCRDocument(this);
                }
                return this.mUIOpiniómetroUCRDocument;
            }
        }
        
        public UIOpiniómetroUCRDocument1 UIOpiniómetroUCRDocument1
        {
            get
            {
                if ((this.mUIOpiniómetroUCRDocument1 == null))
                {
                    this.mUIOpiniómetroUCRDocument1 = new UIOpiniómetroUCRDocument1(this);
                }
                return this.mUIOpiniómetroUCRDocument1;
            }
        }
        
        public UIOpiniómetroUCRDocument2 UIOpiniómetroUCRDocument2
        {
            get
            {
                if ((this.mUIOpiniómetroUCRDocument2 == null))
                {
                    this.mUIOpiniómetroUCRDocument2 = new UIOpiniómetroUCRDocument2(this);
                }
                return this.mUIOpiniómetroUCRDocument2;
            }
        }
        
        public UIOpiniómetroUCRDocument11 UIOpiniómetroUCRDocument11
        {
            get
            {
                if ((this.mUIOpiniómetroUCRDocument11 == null))
                {
                    this.mUIOpiniómetroUCRDocument11 = new UIOpiniómetroUCRDocument11(this);
                }
                return this.mUIOpiniómetroUCRDocument11;
            }
        }
        #endregion
        
        #region Fields
        private UIOpiniómetroUCRDocument mUIOpiniómetroUCRDocument;
        
        private UIOpiniómetroUCRDocument1 mUIOpiniómetroUCRDocument1;
        
        private UIOpiniómetroUCRDocument2 mUIOpiniómetroUCRDocument2;
        
        private UIOpiniómetroUCRDocument11 mUIOpiniómetroUCRDocument11;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIOpiniómetroUCRDocument : HtmlDocument
    {
        
        public UIOpiniómetroUCRDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Opiniómetro@UCR";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Opiniometro_WebApp/CursosMatriculados";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost/Opiniometro_WebApp/CursosMatriculados";
            this.WindowTitles.Add("Opiniómetro@UCR");
            #endregion
        }
        
        #region Properties
        public UITablagruposMatriculaTable UITablagruposMatriculaTable
        {
            get
            {
                if ((this.mUITablagruposMatriculaTable == null))
                {
                    this.mUITablagruposMatriculaTable = new UITablagruposMatriculaTable(this);
                }
                return this.mUITablagruposMatriculaTable;
            }
        }
        #endregion
        
        #region Fields
        private UITablagruposMatriculaTable mUITablagruposMatriculaTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UITablagruposMatriculaTable : HtmlTable
    {
        
        public UITablagruposMatriculaTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = "tabla-gruposMatriculado";
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "Sigla \r\n\r\nCurso \r\n\r\nSemestre \r\n\r\nAño \r\n\r";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "width=\"100\" class=\"table table-sm table-hover\" id=\"tabla-gruposMatriculado\" cells" +
                "pacing=\"0\"";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "2";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "6";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = "table table-sm table-hover";
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("Opiniómetro@UCR");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIEvaluacióndeProfesorHyperlink
        {
            get
            {
                if ((this.mUIEvaluacióndeProfesorHyperlink == null))
                {
                    this.mUIEvaluacióndeProfesorHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIEvaluacióndeProfesorHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIEvaluacióndeProfesorHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIEvaluacióndeProfesorHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIEvaluacióndeProfesorHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Evaluación de Profesores";
                    this.mUIEvaluacióndeProfesorHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Opiniometro_WebApp/FormularioCurso";
                    this.mUIEvaluacióndeProfesorHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIEvaluacióndeProfesorHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost/Opiniometro_WebApp/FormularioCurso?cedulaEstudiante=116720500&co" +
                        "digoForm=131313";
                    this.mUIEvaluacióndeProfesorHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIEvaluacióndeProfesorHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Opiniometro_WebApp/FormularioCurs";
                    this.mUIEvaluacióndeProfesorHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIEvaluacióndeProfesorHyperlink.WindowTitles.Add("Opiniómetro@UCR");
                    #endregion
                }
                return this.mUIEvaluacióndeProfesorHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIEvaluacióndeProfesorHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIOpiniómetroUCRDocument1 : HtmlDocument
    {
        
        public UIOpiniómetroUCRDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Opiniómetro@UCR";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Opiniometro_WebApp/Auth/Login";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost/Opiniometro_WebApp/Auth/Login?ReturnUrl=%2FOpiniometro_WebApp%2F" +
                "";
            this.WindowTitles.Add("Opiniómetro@UCR");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UICorreoInstitucionalEdit
        {
            get
            {
                if ((this.mUICorreoInstitucionalEdit == null))
                {
                    this.mUICorreoInstitucionalEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUICorreoInstitucionalEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUICorreoInstitucionalEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "CorreoInstitucional";
                    this.mUICorreoInstitucionalEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUICorreoInstitucionalEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUICorreoInstitucionalEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUICorreoInstitucionalEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUICorreoInstitucionalEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"CorreoInstitucional\" class=\"form-c";
                    this.mUICorreoInstitucionalEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUICorreoInstitucionalEdit.WindowTitles.Add("Opiniómetro@UCR");
                    #endregion
                }
                return this.mUICorreoInstitucionalEdit;
            }
        }
        
        public HtmlEdit UIContrasenaEdit
        {
            get
            {
                if ((this.mUIContrasenaEdit == null))
                {
                    this.mUIContrasenaEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIContrasenaEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUIContrasenaEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Contrasena";
                    this.mUIContrasenaEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIContrasenaEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIContrasenaEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIContrasenaEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIContrasenaEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Contrasena\" class=\"form-control\" t";
                    this.mUIContrasenaEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIContrasenaEdit.WindowTitles.Add("Opiniómetro@UCR");
                    #endregion
                }
                return this.mUIContrasenaEdit;
            }
        }
        
        public HtmlInputButton UIIngresarButton
        {
            get
            {
                if ((this.mUIIngresarButton == null))
                {
                    this.mUIIngresarButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIIngresarButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUIIngresarButton.SearchProperties[HtmlButton.PropertyNames.Name] = "Ingresar";
                    this.mUIIngresarButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Ingresar";
                    this.mUIIngresarButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIIngresarButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIIngresarButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-default";
                    this.mUIIngresarButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "name=\"Ingresar\" class=\"btn btn-default\" ";
                    this.mUIIngresarButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "3";
                    this.mUIIngresarButton.WindowTitles.Add("Opiniómetro@UCR");
                    #endregion
                }
                return this.mUIIngresarButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUICorreoInstitucionalEdit;
        
        private HtmlEdit mUIContrasenaEdit;
        
        private HtmlInputButton mUIIngresarButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIOpiniómetroUCRDocument2 : HtmlDocument
    {
        
        public UIOpiniómetroUCRDocument2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Opiniómetro@UCR";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Opiniometro_WebApp/Perfil/Cambiar";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost/Opiniometro_WebApp/Perfil/Cambiar";
            this.WindowTitles.Add("Opiniómetro@UCR");
            #endregion
        }
        
        #region Properties
        public HtmlComboBox UIPerfilSeleccionadoComboBox
        {
            get
            {
                if ((this.mUIPerfilSeleccionadoComboBox == null))
                {
                    this.mUIPerfilSeleccionadoComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUIPerfilSeleccionadoComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "perfilSeleccionado";
                    this.mUIPerfilSeleccionadoComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "perfilSeleccionado";
                    this.mUIPerfilSeleccionadoComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = null;
                    this.mUIPerfilSeleccionadoComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUIPerfilSeleccionadoComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUIPerfilSeleccionadoComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "3";
                    this.mUIPerfilSeleccionadoComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "form-control";
                    this.mUIPerfilSeleccionadoComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"perfilSeleccionado\" class=\"form-co";
                    this.mUIPerfilSeleccionadoComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "1";
                    this.mUIPerfilSeleccionadoComboBox.WindowTitles.Add("Opiniómetro@UCR");
                    #endregion
                }
                return this.mUIPerfilSeleccionadoComboBox;
            }
        }
        
        public HtmlInputButton UIAceptarButton
        {
            get
            {
                if ((this.mUIAceptarButton == null))
                {
                    this.mUIAceptarButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIAceptarButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUIAceptarButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIAceptarButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Aceptar";
                    this.mUIAceptarButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIAceptarButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIAceptarButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-default";
                    this.mUIAceptarButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-default\" style=\"margin-ri";
                    this.mUIAceptarButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "1";
                    this.mUIAceptarButton.WindowTitles.Add("Opiniómetro@UCR");
                    #endregion
                }
                return this.mUIAceptarButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlComboBox mUIPerfilSeleccionadoComboBox;
        
        private HtmlInputButton mUIAceptarButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIOpiniómetroUCRDocument11 : HtmlDocument
    {
        
        public UIOpiniómetroUCRDocument11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Opiniómetro@UCR";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Opiniometro_WebApp/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost/Opiniometro_WebApp/";
            this.WindowTitles.Add("Opiniómetro@UCR");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIEvaluacionesHyperlink
        {
            get
            {
                if ((this.mUIEvaluacionesHyperlink == null))
                {
                    this.mUIEvaluacionesHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIEvaluacionesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIEvaluacionesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIEvaluacionesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIEvaluacionesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Evaluaciones";
                    this.mUIEvaluacionesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Opiniometro_WebApp/";
                    this.mUIEvaluacionesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIEvaluacionesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost/Opiniometro_WebApp/#";
                    this.mUIEvaluacionesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "dropdown-toggle";
                    this.mUIEvaluacionesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"dropdown-toggle\" role=\"button\" ar";
                    this.mUIEvaluacionesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "13";
                    this.mUIEvaluacionesHyperlink.WindowTitles.Add("Opiniómetro@UCR");
                    #endregion
                }
                return this.mUIEvaluacionesHyperlink;
            }
        }
        
        public HtmlHyperlink UIEvaluarprofesoresHyperlink
        {
            get
            {
                if ((this.mUIEvaluarprofesoresHyperlink == null))
                {
                    this.mUIEvaluarprofesoresHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIEvaluarprofesoresHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIEvaluarprofesoresHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIEvaluarprofesoresHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIEvaluarprofesoresHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Evaluar profesores";
                    this.mUIEvaluarprofesoresHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Opiniometro_WebApp/CursosMatriculados";
                    this.mUIEvaluarprofesoresHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIEvaluarprofesoresHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost/Opiniometro_WebApp/CursosMatriculados";
                    this.mUIEvaluarprofesoresHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIEvaluarprofesoresHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Opiniometro_WebApp/CursosMatricul";
                    this.mUIEvaluarprofesoresHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "17";
                    this.mUIEvaluarprofesoresHyperlink.WindowTitles.Add("Opiniómetro@UCR");
                    #endregion
                }
                return this.mUIEvaluarprofesoresHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIEvaluacionesHyperlink;
        
        private HtmlHyperlink mUIEvaluarprofesoresHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHotmailOutlooknoticiWindow : BrowserWindow
    {
        
        public UIHotmailOutlooknoticiWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Hotmail, Outlook, noticias en video, viajes, autos, vacaciones, moda y mucho más " +
                "- MSN Latinoam";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Hotmail, Outlook, noticias en video, viajes, autos, vacaciones, moda y mucho más " +
                    "- MSN Latinoam");
            this.WindowTitles.Add("http://localhost/Opiniometro_WebApp");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHotmailOutlooknoticiDocument UIHotmailOutlooknoticiDocument
        {
            get
            {
                if ((this.mUIHotmailOutlooknoticiDocument == null))
                {
                    this.mUIHotmailOutlooknoticiDocument = new UIHotmailOutlooknoticiDocument(this);
                }
                return this.mUIHotmailOutlooknoticiDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIHotmailOutlooknoticiDocument mUIHotmailOutlooknoticiDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHotmailOutlooknoticiDocument : HtmlDocument
    {
        
        public UIHotmailOutlooknoticiDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Hotmail, Outlook, noticias en video, viajes, autos, vacaciones, moda y mucho más " +
                "- MSN Latinoamérica";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/es-xl/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://www.msn.com/es-xl/?ocid=iehp";
            this.WindowTitles.Add("Hotmail, Outlook, noticias en video, viajes, autos, vacaciones, moda y mucho más " +
                    "- MSN Latinoam");
            #endregion
        }
        
        #region Properties
        public UIMainCustom UIMainCustom
        {
            get
            {
                if ((this.mUIMainCustom == null))
                {
                    this.mUIMainCustom = new UIMainCustom(this);
                }
                return this.mUIMainCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIMainCustom mUIMainCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIMainCustom : HtmlCustom
    {
        
        public UIMainCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "main";
            this.SearchProperties["Id"] = "main";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=\"main\" role=\"main\" data-m=\'{\"i\":18,\"n";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("Hotmail, Outlook, noticias en video, viajes, autos, vacaciones, moda y mucho más " +
                    "- MSN Latinoam");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIOfficeHyperlink
        {
            get
            {
                if ((this.mUIOfficeHyperlink == null))
                {
                    this.mUIOfficeHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIOfficeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIOfficeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIOfficeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = "_blank";
                    this.mUIOfficeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Office";
                    this.mUIOfficeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/c/1239701/439025/7804";
                    this.mUIOfficeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIOfficeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://afflnk.microsoft.com/c/1239701/439025/7804?sharedid=PRIME_ESXL_HP_ME&u=htt" +
                        "ps://www.office.com/?omkt=es-xl%26WT.mc_id=MSN_site";
                    this.mUIOfficeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIOfficeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"//afflnk.microsoft.com/c/1239701/4";
                    this.mUIOfficeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "5";
                    this.mUIOfficeHyperlink.WindowTitles.Add("Hotmail, Outlook, noticias en video, viajes, autos, vacaciones, moda y mucho más " +
                            "- MSN Latinoam");
                    #endregion
                }
                return this.mUIOfficeHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIOfficeHyperlink;
        #endregion
    }
}
