// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Opiniometro_WebAppUITest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Se intenta crear una pregunta
        /// </summary>
        public void PruebaIntentoCrearPregunta()
        {
            #region Variable Declarations
            HtmlEdit uICorreoInstitucionalEdit = this.UIOpiniómetroUCRInternWindow.UIOpiniómetroUCRDocument.UICorreoInstitucionalEdit;
            HtmlInputButton uIIngresarButton = this.UIOpiniómetroUCRInternWindow.UIOpiniómetroUCRDocument.UIIngresarButton;
            HtmlInputButton uIAceptarButton = this.UIOpiniómetroUCRInternWindow.UIOpiniómetroUCRDocument1.UIAceptarButton;
            WinMenuItem uIAddressMenuItem = this.UIOpiniómetroUCRInternWindow.UIAddressComboControlToolBar.UIAddressMenuItem;
            BrowserWindow uIOpiniómetroUCRInternWindow = this.UIOpiniómetroUCRInternWindow;
            #endregion

            // Type '' in 'CorreoInstitucional' text box
            uICorreoInstitucionalEdit.Text = this.PruebaIntentoCrearPreguntaParams.UICorreoInstitucionalEditText;

            // Click 'CorreoInstitucional' text box
            Mouse.Click(uICorreoInstitucionalEdit, new Point(39, 13));

            // Type 'admin@ucr.ac.cr' in 'CorreoInstitucional' text box
            uICorreoInstitucionalEdit.Text = this.PruebaIntentoCrearPreguntaParams.UICorreoInstitucionalEditText1;

            // Click 'Ingresar' button
            Mouse.Click(uIIngresarButton, new Point(20, 25));

            // Click 'Aceptar' button
            Mouse.Click(uIAceptarButton, new Point(24, 11));

            // Click 'Address' menu item
            Mouse.Click(uIAddressMenuItem, new Point(234, 3));

            // Go to web page 'http://localhost/Opiniometro_WebApp/Item/create'
            uIOpiniómetroUCRInternWindow.NavigateToUrl(new System.Uri(this.PruebaIntentoCrearPreguntaParams.UIOpiniómetroUCRInternWindowUrl));
        }
        
        /// <summary>
        /// Prueba para Ingreso a la Aplicacion
        /// </summary>
        public void PruebaIngresoAplicacion()
        {
            #region Variable Declarations
            WinMenuItem uIAddressMenuItem = this.UIHomePageInternetExplWindow.UIAddressComboControlToolBar.UIAddressMenuItem;
            BrowserWindow uIHomePageInternetExplWindow = this.UIHomePageInternetExplWindow;
            #endregion

            // Go to web page 'http://go.microsoft.com/fwlink/p/?LinkId=255141' using new browser instance
            this.UIHomePageInternetExplWindow.LaunchUrl(new System.Uri(this.PruebaIngresoAplicacionParams.UIHomePageInternetExplWindowUrl));

            // Click 'Address' menu item
            Mouse.Click(uIAddressMenuItem, new Point(230, 4));

            // Go to web page 'http://localhost/Opiniometro_WebApp'
            uIHomePageInternetExplWindow.NavigateToUrl(new System.Uri(this.PruebaIngresoAplicacionParams.UIHomePageInternetExplWindowUrl1));
        }
        
        #region Properties
        public virtual PruebaIntentoCrearPreguntaParams PruebaIntentoCrearPreguntaParams
        {
            get
            {
                if ((this.mPruebaIntentoCrearPreguntaParams == null))
                {
                    this.mPruebaIntentoCrearPreguntaParams = new PruebaIntentoCrearPreguntaParams();
                }
                return this.mPruebaIntentoCrearPreguntaParams;
            }
        }
        
        public virtual PruebaIngresoAplicacionParams PruebaIngresoAplicacionParams
        {
            get
            {
                if ((this.mPruebaIngresoAplicacionParams == null))
                {
                    this.mPruebaIngresoAplicacionParams = new PruebaIngresoAplicacionParams();
                }
                return this.mPruebaIngresoAplicacionParams;
            }
        }
        
        public UIStartWindow UIStartWindow
        {
            get
            {
                if ((this.mUIStartWindow == null))
                {
                    this.mUIStartWindow = new UIStartWindow();
                }
                return this.mUIStartWindow;
            }
        }
        
        public UIHomePageInternetExplWindow UIHomePageInternetExplWindow
        {
            get
            {
                if ((this.mUIHomePageInternetExplWindow == null))
                {
                    this.mUIHomePageInternetExplWindow = new UIHomePageInternetExplWindow();
                }
                return this.mUIHomePageInternetExplWindow;
            }
        }
        
        public UIOpiniómetroUCRInternWindow UIOpiniómetroUCRInternWindow
        {
            get
            {
                if ((this.mUIOpiniómetroUCRInternWindow == null))
                {
                    this.mUIOpiniómetroUCRInternWindow = new UIOpiniómetroUCRInternWindow();
                }
                return this.mUIOpiniómetroUCRInternWindow;
            }
        }
        #endregion
        
        #region Fields
        private PruebaIntentoCrearPreguntaParams mPruebaIntentoCrearPreguntaParams;
        
        private PruebaIngresoAplicacionParams mPruebaIngresoAplicacionParams;
        
        private UIStartWindow mUIStartWindow;
        
        private UIHomePageInternetExplWindow mUIHomePageInternetExplWindow;
        
        private UIOpiniómetroUCRInternWindow mUIOpiniómetroUCRInternWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'PruebaIntentoCrearPregunta'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class PruebaIntentoCrearPreguntaParams
    {
        
        #region Fields
        /// <summary>
        /// Type '' in 'CorreoInstitucional' text box
        /// </summary>
        public string UICorreoInstitucionalEditText = "";
        
        /// <summary>
        /// Type 'admin@ucr.ac.cr' in 'CorreoInstitucional' text box
        /// </summary>
        public string UICorreoInstitucionalEditText1 = "admin@ucr.ac.cr";
        
        /// <summary>
        /// Go to web page 'http://localhost/Opiniometro_WebApp/Item/create'
        /// </summary>
        public string UIOpiniómetroUCRInternWindowUrl = "http://localhost/Opiniometro_WebApp/Item/create";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'PruebaIngresoAplicacion'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class PruebaIngresoAplicacionParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://go.microsoft.com/fwlink/p/?LinkId=255141' using new browser instance
        /// </summary>
        public string UIHomePageInternetExplWindowUrl = "http://go.microsoft.com/fwlink/p/?LinkId=255141";
        
        /// <summary>
        /// Go to web page 'http://localhost/Opiniometro_WebApp'
        /// </summary>
        public string UIHomePageInternetExplWindowUrl1 = "http://localhost/Opiniometro_WebApp";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIStartWindow : WinWindow
    {
        
        public UIStartWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Start";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Start";
            this.WindowTitles.Add("Start");
            #endregion
        }
        
        #region Properties
        public WinButton UIStartButton
        {
            get
            {
                if ((this.mUIStartButton == null))
                {
                    this.mUIStartButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIStartButton.SearchProperties[WinButton.PropertyNames.Name] = "Start";
                    this.mUIStartButton.WindowTitles.Add("Start");
                    #endregion
                }
                return this.mUIStartButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIStartButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHomePageInternetExplWindow : BrowserWindow
    {
        
        public UIHomePageInternetExplWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Home Page";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Home Page");
            this.WindowTitles.Add("Hotmail, Outlook, noticias en video, viajes, autos, vacaciones, moda y mucho más " +
                    "- MSN Latinoam");
            this.WindowTitles.Add("Blank Page");
            this.WindowTitles.Add("http://localhost/Opiniometro_WebApp");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIAddressBarClient UIAddressBarClient
        {
            get
            {
                if ((this.mUIAddressBarClient == null))
                {
                    this.mUIAddressBarClient = new UIAddressBarClient(this);
                }
                return this.mUIAddressBarClient;
            }
        }
        
        public UIHotmailOutlooknoticiDocument UIHotmailOutlooknoticiDocument
        {
            get
            {
                if ((this.mUIHotmailOutlooknoticiDocument == null))
                {
                    this.mUIHotmailOutlooknoticiDocument = new UIHotmailOutlooknoticiDocument(this);
                }
                return this.mUIHotmailOutlooknoticiDocument;
            }
        }
        
        public UIAddressComboControlToolBar UIAddressComboControlToolBar
        {
            get
            {
                if ((this.mUIAddressComboControlToolBar == null))
                {
                    this.mUIAddressComboControlToolBar = new UIAddressComboControlToolBar(this);
                }
                return this.mUIAddressComboControlToolBar;
            }
        }
        #endregion
        
        #region Fields
        private UIAddressBarClient mUIAddressBarClient;
        
        private UIHotmailOutlooknoticiDocument mUIHotmailOutlooknoticiDocument;
        
        private UIAddressComboControlToolBar mUIAddressComboControlToolBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIAddressBarClient : WinClient
    {
        
        public UIAddressBarClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Address Bar";
            this.WindowTitles.Add("Home Page");
            this.WindowTitles.Add("Hotmail, Outlook, noticias en video, viajes, autos, vacaciones, moda y mucho más " +
                    "- MSN Latinoam");
            this.WindowTitles.Add("Blank Page");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAddressandsearchusinEdit
        {
            get
            {
                if ((this.mUIAddressandsearchusinEdit == null))
                {
                    this.mUIAddressandsearchusinEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAddressandsearchusinEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Address and search using Bing";
                    this.mUIAddressandsearchusinEdit.WindowTitles.Add("Home Page");
                    this.mUIAddressandsearchusinEdit.WindowTitles.Add("Hotmail, Outlook, noticias en video, viajes, autos, vacaciones, moda y mucho más " +
                            "- MSN Latinoam");
                    this.mUIAddressandsearchusinEdit.WindowTitles.Add("Blank Page");
                    #endregion
                }
                return this.mUIAddressandsearchusinEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAddressandsearchusinEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHotmailOutlooknoticiDocument : HtmlDocument
    {
        
        public UIHotmailOutlooknoticiDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Hotmail, Outlook, noticias en video, viajes, autos, vacaciones, moda y mucho más " +
                "- MSN Latinoamérica";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/es-xl/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://www.msn.com/es-xl/?ocid=iehp";
            this.WindowTitles.Add("Hotmail, Outlook, noticias en video, viajes, autos, vacaciones, moda y mucho más " +
                    "- MSN Latinoam");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIHeadercommonCustom
        {
            get
            {
                if ((this.mUIHeadercommonCustom == null))
                {
                    this.mUIHeadercommonCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIHeadercommonCustom.SearchProperties["TagName"] = "HEADER";
                    this.mUIHeadercommonCustom.SearchProperties["Id"] = "header-common";
                    this.mUIHeadercommonCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIHeadercommonCustom.FilterProperties["Class"] = "no-overlay";
                    this.mUIHeadercommonCustom.FilterProperties["ControlDefinition"] = "class=\"no-overlay\" id=\"header-common\" ro";
                    this.mUIHeadercommonCustom.FilterProperties["TagInstance"] = "1";
                    this.mUIHeadercommonCustom.WindowTitles.Add("Hotmail, Outlook, noticias en video, viajes, autos, vacaciones, moda y mucho más " +
                            "- MSN Latinoam");
                    #endregion
                }
                return this.mUIHeadercommonCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIHeadercommonCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIAddressComboControlToolBar : WinToolBar
    {
        
        public UIAddressComboControlToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Address Combo Control";
            this.WindowTitles.Add("Hotmail, Outlook, noticias en video, viajes, autos, vacaciones, moda y mucho más " +
                    "- MSN Latinoam");
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIAddressMenuItem
        {
            get
            {
                if ((this.mUIAddressMenuItem == null))
                {
                    this.mUIAddressMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIAddressMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Address";
                    this.mUIAddressMenuItem.WindowTitles.Add("Hotmail, Outlook, noticias en video, viajes, autos, vacaciones, moda y mucho más " +
                            "- MSN Latinoam");
                    #endregion
                }
                return this.mUIAddressMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIAddressMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIOpiniómetroUCRInternWindow : BrowserWindow
    {
        
        public UIOpiniómetroUCRInternWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Opiniómetro@UCR";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Opiniómetro@UCR");
            this.WindowTitles.Add("http://localhost/Opiniometro_WebApp/Item/create");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIOpiniómetroUCRDocument UIOpiniómetroUCRDocument
        {
            get
            {
                if ((this.mUIOpiniómetroUCRDocument == null))
                {
                    this.mUIOpiniómetroUCRDocument = new UIOpiniómetroUCRDocument(this);
                }
                return this.mUIOpiniómetroUCRDocument;
            }
        }
        
        public UIOpiniómetroUCRDocument1 UIOpiniómetroUCRDocument1
        {
            get
            {
                if ((this.mUIOpiniómetroUCRDocument1 == null))
                {
                    this.mUIOpiniómetroUCRDocument1 = new UIOpiniómetroUCRDocument1(this);
                }
                return this.mUIOpiniómetroUCRDocument1;
            }
        }
        
        public UIAddressComboControlToolBar1 UIAddressComboControlToolBar
        {
            get
            {
                if ((this.mUIAddressComboControlToolBar == null))
                {
                    this.mUIAddressComboControlToolBar = new UIAddressComboControlToolBar1(this);
                }
                return this.mUIAddressComboControlToolBar;
            }
        }
        #endregion
        
        #region Fields
        private UIOpiniómetroUCRDocument mUIOpiniómetroUCRDocument;
        
        private UIOpiniómetroUCRDocument1 mUIOpiniómetroUCRDocument1;
        
        private UIAddressComboControlToolBar1 mUIAddressComboControlToolBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIOpiniómetroUCRDocument : HtmlDocument
    {
        
        public UIOpiniómetroUCRDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Opiniómetro@UCR";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Opiniometro_WebApp/Auth/Login";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost/Opiniometro_WebApp/Auth/Login?ReturnUrl=%2FOpiniometro_WebApp%2F" +
                "";
            this.WindowTitles.Add("Opiniómetro@UCR");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UICorreoInstitucionalEdit
        {
            get
            {
                if ((this.mUICorreoInstitucionalEdit == null))
                {
                    this.mUICorreoInstitucionalEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUICorreoInstitucionalEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUICorreoInstitucionalEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "CorreoInstitucional";
                    this.mUICorreoInstitucionalEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUICorreoInstitucionalEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUICorreoInstitucionalEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUICorreoInstitucionalEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUICorreoInstitucionalEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"CorreoInstitucional\" class=\"form-c";
                    this.mUICorreoInstitucionalEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUICorreoInstitucionalEdit.WindowTitles.Add("Opiniómetro@UCR");
                    #endregion
                }
                return this.mUICorreoInstitucionalEdit;
            }
        }
        
        public HtmlInputButton UIIngresarButton
        {
            get
            {
                if ((this.mUIIngresarButton == null))
                {
                    this.mUIIngresarButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIIngresarButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUIIngresarButton.SearchProperties[HtmlButton.PropertyNames.Name] = "Ingresar";
                    this.mUIIngresarButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Ingresar";
                    this.mUIIngresarButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIIngresarButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIIngresarButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-default";
                    this.mUIIngresarButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "name=\"Ingresar\" class=\"btn btn-default\" ";
                    this.mUIIngresarButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "3";
                    this.mUIIngresarButton.WindowTitles.Add("Opiniómetro@UCR");
                    #endregion
                }
                return this.mUIIngresarButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUICorreoInstitucionalEdit;
        
        private HtmlInputButton mUIIngresarButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIOpiniómetroUCRDocument1 : HtmlDocument
    {
        
        public UIOpiniómetroUCRDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Opiniómetro@UCR";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Opiniometro_WebApp/Perfil/Cambiar";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost/Opiniometro_WebApp/Perfil/Cambiar";
            this.WindowTitles.Add("Opiniómetro@UCR");
            #endregion
        }
        
        #region Properties
        public HtmlInputButton UIAceptarButton
        {
            get
            {
                if ((this.mUIAceptarButton == null))
                {
                    this.mUIAceptarButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIAceptarButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUIAceptarButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIAceptarButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Aceptar";
                    this.mUIAceptarButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIAceptarButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIAceptarButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-default";
                    this.mUIAceptarButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-default\" style=\"margin-ri";
                    this.mUIAceptarButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "1";
                    this.mUIAceptarButton.WindowTitles.Add("Opiniómetro@UCR");
                    #endregion
                }
                return this.mUIAceptarButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlInputButton mUIAceptarButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIAddressComboControlToolBar1 : WinToolBar
    {
        
        public UIAddressComboControlToolBar1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Address Combo Control";
            this.WindowTitles.Add("Opiniómetro@UCR");
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIAddressMenuItem
        {
            get
            {
                if ((this.mUIAddressMenuItem == null))
                {
                    this.mUIAddressMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIAddressMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Address";
                    this.mUIAddressMenuItem.WindowTitles.Add("Opiniómetro@UCR");
                    #endregion
                }
                return this.mUIAddressMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIAddressMenuItem;
        #endregion
    }
}
