// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Opiniometro_UITest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Se mete al link de opiniometro
        /// </summary>
        public void InicializarOpiniometro()
        {
            #region Variable Declarations
            WinPane uIItemPane = this.UINuevapestañaGoogleChWindow.UIItemGroup.UIItemPane;
            WinEdit uIBarradedireccionesydEdit = this.UINuevapestañaGoogleChWindow.UIItemGroup.UIBarradedireccionesydEdit;
            #endregion

            // Click pane
            Mouse.Click(uIItemPane, new Point(479, 15));

            // Type 'localhost/Opiniometro_WebApp/Auth/Login?ReturnUrl=%2FOpiniometro_WebApp%2F' in 'Barra de direcciones y de búsqueda' text box
            uIBarradedireccionesydEdit.Text = this.InicializarOpiniometroParams.UIBarradedireccionesydEditText;
        }
        
        /// <summary>
        /// prueba ingreso aplicacion
        /// </summary>
        public void IngresoAplicacion()
        {
            #region Variable Declarations
            WinPane uIItemPane = this.UINuevapestañaGoogleChWindow.UIItemGroup.UIItemPane;
            WinEdit uIBarradedireccionesydEdit = this.UINuevapestañaGoogleChWindow.UIItemGroup.UIBarradedireccionesydEdit;
            #endregion

            // Click pane
            Mouse.Click(uIItemPane, new Point(611, 12));

            // Type 'localhost/Opiniometro_WebApp' in 'Barra de direcciones y de búsqueda' text box
            uIBarradedireccionesydEdit.Text = this.IngresoAplicacionParams.UIBarradedireccionesydEditText;
        }
        
        #region Properties
        public virtual InicializarOpiniometroParams InicializarOpiniometroParams
        {
            get
            {
                if ((this.mInicializarOpiniometroParams == null))
                {
                    this.mInicializarOpiniometroParams = new InicializarOpiniometroParams();
                }
                return this.mInicializarOpiniometroParams;
            }
        }
        
        public virtual IngresoAplicacionParams IngresoAplicacionParams
        {
            get
            {
                if ((this.mIngresoAplicacionParams == null))
                {
                    this.mIngresoAplicacionParams = new IngresoAplicacionParams();
                }
                return this.mIngresoAplicacionParams;
            }
        }
        
        public UINuevapestañaGoogleChWindow UINuevapestañaGoogleChWindow
        {
            get
            {
                if ((this.mUINuevapestañaGoogleChWindow == null))
                {
                    this.mUINuevapestañaGoogleChWindow = new UINuevapestañaGoogleChWindow();
                }
                return this.mUINuevapestañaGoogleChWindow;
            }
        }
        #endregion
        
        #region Fields
        private InicializarOpiniometroParams mInicializarOpiniometroParams;
        
        private IngresoAplicacionParams mIngresoAplicacionParams;
        
        private UINuevapestañaGoogleChWindow mUINuevapestañaGoogleChWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'InicializarOpiniometro'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class InicializarOpiniometroParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'localhost/Opiniometro_WebApp/Auth/Login?ReturnUrl=%2FOpiniometro_WebApp%2F' in 'Barra de direcciones y de búsqueda' text box
        /// </summary>
        public string UIBarradedireccionesydEditText = "localhost/Opiniometro_WebApp/Auth/Login?ReturnUrl=%2FOpiniometro_WebApp%2F";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'IngresoAplicacion'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class IngresoAplicacionParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'localhost/Opiniometro_WebApp' in 'Barra de direcciones y de búsqueda' text box
        /// </summary>
        public string UIBarradedireccionesydEditText = "localhost/Opiniometro_WebApp";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UINuevapestañaGoogleChWindow : WinWindow
    {
        
        public UINuevapestañaGoogleChWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Nueva pestaña - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("Nueva pestaña - Google Chrome");
            #endregion
        }
        
        #region Properties
        public UIItemGroup UIItemGroup
        {
            get
            {
                if ((this.mUIItemGroup == null))
                {
                    this.mUIItemGroup = new UIItemGroup(this);
                }
                return this.mUIItemGroup;
            }
        }
        #endregion
        
        #region Fields
        private UIItemGroup mUIItemGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemGroup : WinGroup
    {
        
        public UIItemGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Nueva pestaña - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinPane UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new WinPane(this);
                    #region Search Criteria
                    this.mUIItemPane.SearchProperties[WinControl.PropertyNames.Instance] = "2";
                    this.mUIItemPane.WindowTitles.Add("Nueva pestaña - Google Chrome");
                    #endregion
                }
                return this.mUIItemPane;
            }
        }
        
        public WinEdit UIBarradedireccionesydEdit
        {
            get
            {
                if ((this.mUIBarradedireccionesydEdit == null))
                {
                    this.mUIBarradedireccionesydEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIBarradedireccionesydEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Barra de direcciones y de búsqueda";
                    this.mUIBarradedireccionesydEdit.WindowTitles.Add("Nueva pestaña - Google Chrome");
                    #endregion
                }
                return this.mUIBarradedireccionesydEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinPane mUIItemPane;
        
        private WinEdit mUIBarradedireccionesydEdit;
        #endregion
    }
}
