CREATE TABLE [dbo].[Escalar]
(
	ItemId NVARCHAR(10) NOT NULL,
	Inicio SMALLINT NOT NULL,
	Fin SMALLINT NOT NULL,
	Incremento SMALLINT NOT NULL,
	IsaEstrella BIT,
	CONSTRAINT PK_Escalar PRIMARY KEY(ItemId),
	CONSTRAINT FK_Esc_Ite FOREIGN KEY(ItemId) REFERENCES Item(ItemId)
		ON UPDATE CASCADE
)
