//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opiniometro_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conformado_Item_Sec_Form
    {
        public int ItemId { get; set; }
        public string CodigoFormulario { get; set; }
        public string TituloSeccion { get; set; }
        public string NombreFormulario { get; set; }
    
        public virtual Formulario Formulario { get; set; }
        public virtual Item Item { get; set; }
        public virtual Seccion Seccion { get; set; }
    }
}
