//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opiniometro_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empadronado
    {
        public string CedulaEstudiante { get; set; }
        public byte NumeroEnfasis { get; set; }
        public string SiglaCarrera { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
    }
}
