//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opiniometro_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Escalar
    {
        public string ItemId { get; set; }
        public short Inicio { get; set; }
        public short Fin { get; set; }
        public short Incremento { get; set; }
        public Nullable<bool> IsaEstrella { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
