//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opiniometro_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imparte_View
    {
        public string CedulaProfesor { get; set; }
        public byte Numero { get; set; }
        public string Sigla { get; set; }
        public short Anno { get; set; }
        public byte Semestre { get; set; }
    }
}
