//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opiniometro_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Conformado_Item_Sec_Form = new HashSet<Conformado_Item_Sec_Form>();
            this.Responde = new HashSet<Responde>();
        }

        [StringLength(10, ErrorMessage = "El límite de este campo son 10 caracteres.")]
        [Required(ErrorMessage = "Campo obligatorio: Ingrese un Código.")]
        public string ItemId { get; set; }
        [StringLength(120, ErrorMessage = "El límite de este campo son 120 caracteres.")]
        [Required(ErrorMessage = "Campo obligatorio: Ingrese el Texto de la Pregunta.")]
        public string TextoPregunta { get; set; }
        [Required(ErrorMessage = "Campo obligatorio: Seleccione si Tiene Observación o no.")]
        public Nullable<bool> TieneObservacion { get; set; }
        [Required(ErrorMessage = "Campo obligatorio: Seleccione el Tipo de Pregunta.")]
        public byte TipoPregunta { get; set; }
        [Required(ErrorMessage = "Campo obligatorio: Seleccione el Nombre de la Categoría.")]
        public string NombreCategoria { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conformado_Item_Sec_Form> Conformado_Item_Sec_Form { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Responde> Responde { get; set; }
        public virtual Seleccion_Unica Seleccion_Unica { get; set; }
        public virtual Texto_Libre Texto_Libre { get; set; }
    }
}
