//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opiniometro_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opciones_De_Respuestas_Seleccion_Multiple
    {
        public string ItemId { get; set; }
        public short Orden { get; set; }
        public string OpcionRespuesta { get; set; }
    
        public virtual Seleccion_Multiple Seleccion_Multiple { get; set; }
    }
}
