//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opiniometro_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seleccion_Unica
    {
        public int ItemId { get; set; }
        public Nullable<bool> IsaLikeDislike { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
