//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opiniometro_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelefonoPersona
    {
        public string CedulaPersona { get; set; }
        public string NumeroTelefono { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
