//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opiniometro_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tiene_Grupo_Formulario
    {
        public byte Numero { get; set; }
        public string SiglaCurso { get; set; }
        public string Año { get; set; }
        public byte Ciclo { get; set; }
        public string Codigo { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFinal { get; set; }
    
        public virtual Fecha_Corte Fecha_Corte { get; set; }
        public virtual Grupo Grupo { get; set; }
    }
}
