//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opiniometro_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string CorreoInstitucional { get; set; }
        public string Contrasena { get; set; }
        public bool Activo { get; set; }
        public string Cedula { get; set; }
        public System.Guid Id { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
